project_id = "pgypyipdmrhrutegapsx"

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080"]

[auth.email]
enable_confirmations = false

[functions.generate-conversation-title]
verify_jwt = false

[functions.pediatric-ai-chat]
verify_jwt = true

[functions.upload-file-to-openai]
verify_jwt = true

[functions.delete-conversation-file]
verify_jwt = true